### PR TITLE
Review script for paper "2023SoPh..298..105R" made with predictor "DataLinkerCondenseDetailsWithTemplate"

### PR DESCRIPTION
**Pull request by abuonomo**
*Created by Paper Data Linking Bot*

Please review the download script and instrument details for the paper.

**bibcode**: 2023SoPh..298..105R
**predictor**: DataLinkerCondenseDetailsWithTemplate

### CODE REVIEW

**Comment by abuonomo** [comment]
Correctly represents the data mentioned in paper, but the mk3 and mk4 queries don't return any results. It seems that these instruments are listed in the VSO but might not actually have any data available there since their VSO tables are empty. See [here for mk3](https://sdac.virtualsolar.org/cgi/show_details?instrument=MK3) and [here for mk4](https://sdac.virtualsolar.org/cgi/show_details?instrument=MK4).

**Comment by wafels** [comment]
Mk3 is not listed on the VSO web application for searching data. The VSO documentation is probably out of date. Mk4 is available and access is tested on a daily basis - see https://docs.virtualsolar.org/wiki/VSOHealthReport. The paper surveys all the Mk4 data. There may be too many records for the VSO to return.

Hmmm. This is generating some ideas for me for the VSO.

**Comment by abuonomo** [comment]
Ah, interesting. So how would I successfully query for Mk4 data? I just tried to to limit to one day of Mk4 data and I still don't get any results.
```
mk4_time_range = a.Time('2013-12-30', '2013-12-31')
mk4_instrument = a.Instrument("mk4")
mk4_query = Fido.search(mk4_time_range, mk4_instrument)
```
**UPDATE**: Interestingly, the query succeeds when I ask for data from 2010 instead of 2013. Checking available time ranges...
**UPDATE 2**: Looks like Mk4 was decommissioned August of 2013. See data availability [here](https://mlso.hao.ucar.edu/mlso_data_calendar.php?calyear=2013&calinst=mk4). This explains why that query did not work. Need to double check what the paper says again.
**UPDATE 3**: Okay, so the paper only list the dates by year so it lacked the granularity to say when in the year it shut down. Tricksy, I wonder how we should handle this situation in query script.

**Comment by wafels** [comment]
Mk4 was a ground based coronagraph. Sometimes there are no data because of clouds, or because of operational constraints. What should we assume about the user's knowledge of the operational nature of the instrument that took the data?

**Pull request closed without merging**
